# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: augustodev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: nestjs-personwallet-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: nestjs-personwallet-api

provider:
  name: aws
  runtime: nodejs20.x
  architecture: x86_64

plugins:  
  - "@sls-next/serverless-component"

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: ANY  
          cors:
            origin: "*"  # Permite todas as origens
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - X-Forwarded-For
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Accept
              - Accept-Encoding
              - Host
              - Origin
              - Connection
              - User-Agent
              - Referer
              - Cache-Control
              - X-Requested-With
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      - http:
          path: /{proxy+}
          method: ANY  
          cors:
            origin: "*"  # Permite todas as origens
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - X-Forwarded-For
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Accept
              - Accept-Encoding
              - Host
              - Origin
              - Connection
              - User-Agent
              - Referer
              - Cache-Control
              - X-Requested-With
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH